services:
  - type: web
    name: gchatbot
    env: python
    plan: free
    numInstances: 1
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn gchatbot:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.x