services:
  - type: web
    name: chatbot-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn gchatbot:app"
    envVars:
      - key: PORT
        value: 10000  # or let Render set it dynamically
